on:
  push:
    tags:
      - "v*"

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Build project
        run: |
          curl -L -o cyclonedx-cli https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.7.0/cyclonedx-linux-x64
          chmod a+x cyclonedx-cli
          make sbom

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: *bom*
